/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodavelha;

/**
 *
 * @author Leandro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        foto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadjogador = new javax.swing.JMenuItem();
        cadcampeonato = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        velha = new javax.swing.JMenuItem();
        colocacao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        manual = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogodavelha/goku.jpg"))); // NOI18N

        jMenu1.setText("Cadastro");

        cadjogador.setText("CadastrarJogador");
        cadjogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadjogadorActionPerformed(evt);
            }
        });
        jMenu1.add(cadjogador);

        cadcampeonato.setText("CadastrarCampeonato");
        cadcampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadcampeonatoActionPerformed(evt);
            }
        });
        jMenu1.add(cadcampeonato);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jogo");

        velha.setText("Jogo da Velha");
        velha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velhaActionPerformed(evt);
            }
        });
        jMenu2.add(velha);

        colocacao.setText("Tabela Colocação Campeonato");
        colocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colocacaoActionPerformed(evt);
            }
        });
        jMenu2.add(colocacao);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ajuda");

        manual.setText("Manual");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });
        jMenu4.add(manual);

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        jMenu4.add(sobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        Manual ma= new Manual(this, rootPaneCheckingEnabled);
        ma.setVisible(true);
    }//GEN-LAST:event_manualActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        Sobre so= new Sobre(this, rootPaneCheckingEnabled);
        so.setVisible(true);
    }//GEN-LAST:event_sobreActionPerformed

    private void velhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velhaActionPerformed
        JogodaVelha ve=new JogodaVelha();
        ve.setVisible(true);
    }//GEN-LAST:event_velhaActionPerformed

    private void cadjogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadjogadorActionPerformed
        ListaJogador cad= new ListaJogador(this, rootPaneCheckingEnabled);
        cad.setVisible(true);
    }//GEN-LAST:event_cadjogadorActionPerformed

    private void cadcampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadcampeonatoActionPerformed
        ListaCampeonato cad= new ListaCampeonato(this, rootPaneCheckingEnabled);
        cad.setVisible(true);
    }//GEN-LAST:event_cadcampeonatoActionPerformed

    private void colocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocacaoActionPerformed
        ColocacaoCampeonato col= new ColocacaoCampeonato();
        col.setVisible(true);
    }//GEN-LAST:event_colocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadcampeonato;
    private javax.swing.JMenuItem cadjogador;
    private javax.swing.JMenuItem colocacao;
    private javax.swing.JLabel foto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem manual;
    private javax.swing.JMenuItem sobre;
    private javax.swing.JMenuItem velha;
    // End of variables declaration//GEN-END:variables
}
